FROM siestacat/php-apache-node:latest

USER root

RUN apt-get update -yqq && \
    apt-get install --no-install-recommends -yqq ripgrep \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

USER www-data

ENV PATH=/var/www/.local/bin:${PATH}

RUN npm install -g @anthropic-ai/claude-code

SHELL ["/bin/bash", "-c"]

RUN claude --version